/***************************************************************
* file: TitleFrame.java
* author: 
* class: CS 245 – Computer Graphics
*
* assignment: Quarter Project
* date last modified: 9/27/17
*
* purpose: 
*      
****************************************************************/
package Main;


public class TitleFrame extends javax.swing.JFrame {
    public TitleFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        TeamName = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Title.setText("CS 245 Quarter Project");
        getContentPane().add(Title);
        Title.setBounds(340, 50, 200, 14);

        TeamName.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        TeamName.setText("Team Diamond Dogs");
        getContentPane().add(TeamName);
        TeamName.setBounds(400, 70, 150, 16);

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/BackGround.jpg"))); // NOI18N
        BackGround.setText("jLabel1");
        BackGround.setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().add(BackGround);
        BackGround.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TitleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel TeamName;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
